Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true
  
### Ansible-c VM ###
  config.vm.define "ansible" do |ansible|
    ansible.vm.box = "geerlingguy/centos7"
    ansible.vm.hostname = "ansible"
	ansible.vm.network "private_network", ip: "192.168.56.30"
  end
  
### Node01 vm ###
   config.vm.define "node01" do |node01|
    node01.vm.box = "geerlingguy/centos7"
    node01.vm.hostname = "node01"
    node01.vm.network "private_network", ip: "192.168.56.31"
	node01.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
	 end
   end
   
### Node02 vm  ####
  config.vm.define "node02" do |node02|
    node02.vm.box = "geerlingguy/centos7"
	node02.vm.hostname = "node02"
    node02.vm.network "private_network", ip: "192.168.56.32"
  end
  
### NOde03 vm  #### 
  config.vm.define "node03" do |node03|
    node03.vm.box = "geerlingguy/centos7"
	node03.vm.hostname = "node03"
    node03.vm.network "private_network", ip: "192.168.56.33"
  end
  
### Node04 vm  ####
  config.vm.define "node04" do |node04|
    node04.vm.box = "geerlingguy/centos7"
	node04.vm.hostname = "node04"
    node04.vm.network "private_network", ip: "192.168.56.34"
  end
end
