Vagrant.configure("2") do |config|

  config.vm.define "docker" do |docker|
    docker.vm.box = "geerlingguy/centos7"
	docker.vm.network "private_network", ip: "192.168.56.16"
	docker.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
   end
  end
end
