# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  # satellite  Node
  config.vm.define "satellite" do |lb|
    lb.vm.box = "iamseth/rhel-7.3"
    lb.vm.hostname = "satellite.example.com"
    lb.vm.network "private_network", ip: "192.168.56.100"
    lb.vm.network "public_network", ip: "192.168.56.102"
    lb.vm.provider "virtualbox" do |v|
      v.name = "satellite"
      v.memory = 2048
      v.cpus = 2
    end
  end
end
