Vagrant.configure("2") do |config|

  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.box = "geerlingguy/centos7"
	jenkins.vm.network "private_network", ip: "192.168.56.21"
	jenkins.vm.provider "virtualbox" do |vb|
     vb.memory = "2048"
   end
  end
end

