Vagrant.configure("2") do |config|

  config.vm.define "ansible-c" do |ansible|
    ansible.vm.box = "geerlingguy/centos7"
	ansible.vm.network "private_network", ip: "192.168.56.30"
	ansible.vm.provider "virtualbox" do |vb|
    config.vm.provider "virtualbox" do |v|
       v.memory = 2048
       v.cpus = 2
    end
   end
  end

  config.vm.define "node01" do |node01|
    node01.vm.box = "geerlingguy/centos7"
	node01.vm.network "private_network", ip: "192.168.56.31"
    config.vm.provider "virtualbox" do |v|
        v.memory = 512
     end
  end
  
  config.vm.define "node02" do |node02|
    node02.vm.box = "geerlingguy/centos7"
	node02.vm.network "private_network", ip: "192.168.56.32"
     config.vm.provider "virtualbox" do |v|
        v.memory = 512
        v.cpus = 1
     end
  end

   config.vm.define "node03" do |node03|
    node03.vm.box = "ubuntu/bionic64"
        node03.vm.network "private_network", ip: "192.168.56.33"
     config.vm.provider "virtualbox" do |v|
        v.memory = 512
        v.cpus = 1
     end
  end
end

